### ISSUE TITLE
Questions about comprehension of this paper

### ISSUE THREAD

**Issue by zyuh** [GT-SALT/Adaptive-Compositional-Modules#1]
In the paper, it is said that the initialization of c_{k+1} is -c, and the others are c (c&gt; 0) can increase the tendency to reuse old modules. I have some questions about this:
(1) Is c a constant in the training process? Can c_k be understood as the weight corresponding to the k-th module?
(2) I understand that this can inhibit the effect of new adapter, but how does the model decide whether to add a new adapter in the end? How do you decide which adapter to share for similar tasks?
(3) Is the adapter for the old task constantly updated or fixed?
(4) Whether task identifiers are required for inference？

Looking forward to your reply， best wishes

**Comment by StevenyzZhang** [comment]
Hi, thanks for your interest.

For (1)(2), please refer to section 4.1
In short, we are using learnable weight coefficients lambda to decide where to add the adapter/whether we need to add an adapter. c is the initialization value of lambda, as a hyperparameter to tune.

lambda is changed/learned during the training process, and yeah, it is the weight for its corresponding module. After training, in each transformer layer, we select the module with the biggest weight. (i) If the selected one is an old module, the new task will share this module with the corresponding old tasks. (ii) If the selected one is a new module, we add a new module in this layer for the new task.

For (3), adapters for the old task are fixed during the decision stage. 
During the training stage, if some of the old tasks are replayed (see the last paragraph of section 4.2 for details), (i) For the setting of similar tasks, we updated all adapter modules of the replayed tasks. (ii) For the setting of dissimilar tasks, we updated the adapter modules of the replayed tasks that are shared with the current task.
(In the code, this is related to the option "--partial transfer")

(4) Yes. And we also assume we know the identifiers for all adapter baselines.

**Comment by zyuh** [comment]
Thank you for your clear reply.  I have understood !
